version: "3.8"

networks:
  hazelcast_network:
    driver: bridge
    name: hazelcast_network

services:
  management-center:
    container_name: management-center
    image: hazelcast/management-center:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=middleware:4001  # use service name, not localhost
    networks:
      - hazelcast_network

  middleware:
    container_name: middleware
    image: node:lts-alpine
    restart: unless-stopped
    volumes:
      - ./middleware:/usr/src/app
      - ./hazelcast.yaml:/hazelcast.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: node /usr/src/app/server.js
    ports:
      - "127.0.0.1:3000:4000"
    environment:
      - HZ_PORT_START=4100
      - PU_PORT_START=3100
      - PUBLIC_IP=middleware  # use service name internally
      - MIDDLEWARE_NAME=middleware
      - MIDDLEWARE_PORT=4000
    networks:
      - hazelcast_network

  data-rw:
    container_name: data-rw
    image: node:lts-alpine
    restart: unless-stopped
    volumes:
      - ./data-rw:/usr/src/app
    command: node /usr/src/app/server.js
    networks:
      - hazelcast_network
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: +4rQ29=PE53g-@:@XL1
    volumes:
      - ./volumes/data/rabbitmq/lib:/var/lib/rabbitmq/
      - ./volumes/data/rabbitmq/log:/var/log/rabbitmq
    networks:
      - hazelcast_network

  mariadb:
    container_name: mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --log-bin
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: +4rQ29=PE53g-@:@XL1
      MYSQL_USER: admin
      MYSQL_PASSWORD: +4rQ29=PE53g-@:@XL1
      MYSQL_DATABASE: space-based
      MARIADB_AUTO_UPGRADE: 1
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./volumes/config/mariadb:/etc/mysql/
      - ./volumes/data/mariadb:/var/lib/mysql
    networks:
      - hazelcast_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./volumes/data/grafana:/var/lib/grafana
    ports:
      - "127.0.0.1:80:3000"
    networks:
      - hazelcast_network
    user: "0"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.10
    restart: unless-stopped
    volumes:
      - ./volumes/data/elasticsearch:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    networks:
      - hazelcast_network
    user: "0"
